name: Bandit Security Scan

on:
  push:
    branches: [ dev ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r . -ll
